### ISSUE TITLE
More examples: NodeJS, GO

### ISSUE THREAD

**Issue by sashaaKr** [PacktPublishing/Mastering-Distributed-Tracing#10]
Thanks for the great book, jaeger and this repo.
I just finished reading and went through all the examples, I'm coming from NodeJS, and for me it might be very helpful to see working nodejs examples.
As well there are some chapters that only java examples provide (chapter 11 for example).

I would like to contribute examples for nodejs for chapters 4, 11
And add go example for chapter 11,

WDYT?

**Comment by yurishkuro** [comment]
With OpenTelemetry approaching the GA release it feels a bit wasteful to expend energy on extra examples that use OpenTracing.

FWIW, there is Node.js example for basic instrumentation in https://github.com/yurishkuro/opentracing-tutorial.

And the HotROD chapter already covers logs/metrics integration in Go.

If you're interested in contributing tutorials / examples, I would suggest joining the OpenTelemetry project, there is definitely enough work for everyone there :-)
