### ISSUE TITLE
dep ensure doesn't work 

### ISSUE THREAD

**Issue by zheyiyi** [PacktPublishing/Mastering-Distributed-Tracing#2]
when i try dep ensure on mac terminal, it showed that 
could not find project Gopkg.toml, use dep init to initiate a manifest

**Comment by yurishkuro** [comment]
in which directory are you running dep?

**Comment by yurishkuro** [comment]
the Gopkg file is in `Chapter04/go/`

**Comment by zheyiyi** [comment]
I am run dep in /src/github.com/yurishkuro/microsim, 

zheyis-MBP:microsim zheyiyi$ ls
Dockerfile	Gopkg.toml	README.md	config		model
Gopkg.lock	LICENSE		client		main.go		tracing

**Comment by zheyiyi** [comment]
``
![image](https://user-images.githubusercontent.com/12801407/59979371-18d8ee80-95b5-11e9-8df5-9d86515ff3ce.png)

**Comment by yurishkuro** [comment]
The last line is your answer. You need to clone the repo into `$GOPATH/src/github.com/yurishkuro/microsim`

**Comment by zheyiyi** [comment]
`
![image](https://user-images.githubusercontent.com/12801407/59979459-41adb380-95b6-11e9-801d-7e6302afa55e.png)
`

**Comment by zheyiyi** [comment]
[
![image](https://user-images.githubusercontent.com/12801407/59979470-59853780-95b6-11e9-82f1-621f85eeb6ad.png)
](url)

**Comment by zheyiyi** [comment]
This is really wired. I use cd $GOPATH/src/github.com/yurishkuro, but it said that /src/github.com/yurishkuro/microsim is not within a known GOPATH/src

**Comment by zheyiyi** [comment]
This is the first time I use go, so I don't have any experience on it

**Comment by nilend** [comment]
> This is really wired. I use cd $GOPATH/src/github.com/yurishkuro, but it said that /src/github.com/yurishkuro/microsim is not within a known GOPATH/src

Maybe it's too late but for reference, it is clear your $GOPATH environment variable is not set. You can set it manually by `export GOPATH=(`go env GOPATH`)` or set it permanently by including it in your `.bashrc` or etc and repeat the steps.
