### ISSUE TITLE
why i create $GOPATH/src/github.com/yurishkuro， but  it show /src/github.com/yurishkuro

### ISSUE THREAD

**Issue by zheyiyi** [PacktPublishing/Mastering-Distributed-Tracing#3]
[
![image](https://user-images.githubusercontent.com/12801407/59979557-7a9a5800-95b7-11e9-9126-944a139f9df6.png)
](url)

**Comment by zheyiyi** [comment]
[
![image](https://user-images.githubusercontent.com/12801407/59979579-af0e1400-95b7-11e9-969c-a27f26fb7faf.png)
](url)

**Comment by yurishkuro** [comment]
Given your env, the repo should be cloned into /Users/zheyiyi/go/src/github.com/yurishkuro/microsim

I don't know why you end up with /src/... if you create it there, this is something odd with your setup.
