### ISSUE TITLE
why do you use session window in the flink to process spans

### ISSUE THREAD

**Issue by zheyiyi** [PacktPublishing/Mastering-Distributed-Tracing#5]
Can I ask in this function why do you choose session window in the flink？It is better than time window？ And  how do we identify traceSessionWindow? 

    private static DataStream<Trace> aggregateSpansToTraces(DataStream<Span> spans) {
        return spans //
                .keyBy((KeySelector<Span, String>) span -> span.traceId)
                .window(ProcessingTimeSessionWindows.withGap(traceSessionWindow))
                .apply(new WindowFunction<Span, Trace, String, TimeWindow>() {
                    @Override
                    public void apply(String traceId, TimeWindow window, Iterable<Span> spans, Collector<Trace> out)
                            throws Exception {
                        List<Span> spanList = new ArrayList<>();
                        spans.forEach(spanList::add);

                        Trace trace = new Trace();
                        trace.traceId = traceId;
                        trace.spans = spanList;
                        out.collect(trace);
                    }
                });
    }

**Comment by yurishkuro** [comment]
It's explained in detail in the book. Session window allows aggregation to continue as long as additional spans for the trace keep arriving, which can happen with slow clients. You can tune how long the window stays open after the last span via `traceSessionWindow` parameter; it's a trade-off between getting more complete traces and timeliness of the results.
