### ISSUE TITLE
Why does it work without jaeger-agent?

### ISSUE THREAD

**Issue by zheyiyi** [PacktPublishing/Mastering-Distributed-Tracing#6]
In this docker-compose.yml, you heavn't initiate jaeger agent, why collector still can get trace? 

/Chapter12/docker-compose.yml

**Comment by yurishkuro** [comment]
because the `microsim` trace generator submits spans directly to collector over HTTP. The agent is not necessary. https://github.com/yurishkuro/microsim/blob/f65ddc46b8011358eda59f26d60a75b5c4c27cf3/tracing/init.go#L12
