### ISSUE TITLE
Querying for non-existing user causes NPE

### ISSUE THREAD

**Issue by mikehalma** [PacktPublishing/Mastering-Distributed-Tracing#7]
...I couldn't get the first example from Chapter04 to run.  If you curl for for a user that isn't in the database, you get a null pointer at Chapter04/java/src/main/java/exercise1/HelloController:36 because the title is null.  Just initialise to "" in Person to fix it.

I was gonna submit a PR but Java 11 decided to stick needles in my eyes. Meh.

**Comment by packt-pradeeps** [comment]
@yurishkuro please look into this issue
