### ISSUE TITLE
Chapter 11: logstash port 5000 conflicts with Docker Desktop for Mac

### ISSUE THREAD

**Issue by lakamsani** [PacktPublishing/Mastering-Distributed-Tracing#8]
Hi, Trying out chapter 11. I hit an issue where port 5000 of the logstash docker container had a conflict with port 5000 used by docker for Mac. I [updated the port to 6000](https://github.com/lakamsani/Mastering-Distributed-Tracing/commit/0fa8748766d741c2f3c7faf69cfd8dd282aec9cb), updated logback config files in all the services and seeing the logs in kibana. However figure 11.5 and the related table looks a bit different as shown below. 

![Screen Shot 2019-10-21 at 6 26 11 PM](https://user-images.githubusercontent.com/3322496/67254212-c3accc80-f430-11e9-8f6a-79afcb155ac5.png)
![Screen Shot 2019-10-21 at 6 26 03 PM](https://user-images.githubusercontent.com/3322496/67254214-c4456300-f430-11e9-9d33-50187a7f122d.png)

Is this a new format or some error  related to the above change?

**Comment by yurishkuro** [comment]
The change to the port looks ok to me.

**Comment by lakamsani** [comment]
Sent a PR if  interested.  https://github.com/PacktPublishing/Mastering-Distributed-Tracing/pull/9
